### ISSUE TITLE
home_dir broken

### ISSUE THREAD

**Issue by Zamiell** [justjavac/deno_dirs#1]
Hello, and thanks for the library.

It looks like "https://deno.land/x/home_dir/mod.ts" is a broken link.

Can you take a look?

**Comment by justjavac** [comment]
use https://deno.land/x/dir/home_dir/mod.ts

**Comment by Zamiell** [comment]
thanks.
can you update the readme.md to fix the broken link?
i.e. it literally says to use "https://deno.land/x/home_dir/mod.ts"
